version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - APP_DB_USER=postgres
      - APP_DB_PASS=postgres
      - APP_DB_NAME=foxnode
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  db:
    driver: local